### ISSUE TITLE
Error when using latest emqx 5.8.0 Ubuntu package

### ISSUE THREAD

**Issue by satheesh3** [emqx/tf-aws#6]
When using latest ubuntu package **https://www.emqx.com/en/downloads/broker/5.8.0/emqx-5.8.0-ubuntu24.04-amd64.tar.gz** instead of given 5.0.24. Below is the screenshot of the error. Could someone help me with this.

**Comment by satheesh3** [comment]
<img width="1696" alt="Screenshot 2024-09-12 at 12 31 34 PM" src="https://github.com/user-attachments/assets/1cbb4bf3-d05b-40b2-9bb0-0c5850153202">

**Comment by zmstone** [comment]
Please check if your system is really Ubuntu 24.
Good chance that you are running Ubuntu 20 or 22

**Comment by satheesh3** [comment]
Sorry, yes I figured it out.
